TEST_CASES = {'7{M2Zk7&N': False,
 "T:A'Y\\.": False,
 '8T*sWBr(X5x-P': False,
 'GUeP"1O|M}b3': False,
 'G)4Cd[1tAs': False,
 '3Q7\'UZu%"Vp': False,
 'Xj8dpcq': True,
 "V('2wU": False,
 'uJ4_I|n!<v+J~eR': False,
 '7eH?3o[3': False,
 'BsndxA4Fcwq]': False,
 ' =_c,qW': False,
 'n6(?zArSXp4u': False,
 "sQt|/2'g=^f\\s": False,
 '5IhQxh]/': False,
 '[7`-<wWmz': False,
 'AnA3nBD#': False,
 'T~:^I9Gt`@};8jY': False,
 '?HBH"|9Y': False,
 "X%2'C{GA\\e:O": False,
 'w[ceb&~K:NTq7hw': False,
 'M5vk@': False,
 "$!'\\H^[abqtyT9": False,
 'w==j[%W_qkqo(V': False,
 "'b{BZb8Jq6U[X-b": False,
 '|F1&lw(w-=pgz3%': False,
 'B"q8U`I[L$J': False,
 '%oWduW/2=<3"': False,
 'uK*w!+[': False,
 'Gb}#g&': False,
 'P)Bz4y=i': False,
 'Vu3"\\!': False,
 '^A#H:SCe4f_!xRV': False,
 '~I)c]&': False,
 '4TC.5LUgcM+Y': False,
 ',&/56;bP': False,
 '9Z?=OqyT+': False,
 'a[!#X>SBy;Bw9l': False,
 '0@cn~[\\&,7': False,
 'pE06!BdZtB56vx': False,
 '7|,#&q-?R"^;Kp)': False,
 "#b'=f1Q": False,
 'J%}|x': False,
 ']A(7"wE(': False,
 'YfO.N}5P .9': False,
 'hbTN;qi': False,
 '^w"Z%+<': False,
 '\\r^Qr>Ij4~Mf{l/': False,
 '7RMBX:<8gR': False,
 'kelU2K,hgH\\47-': False,
 '5sW?iEY+#9IfR': False,
 'CfF?7]</GCc;P': False,
 'nDb>*pn': False,
 'N ?pC3 i2': False,
 'LJev9n$|Lor': False,
 'e`RX+$Lw_&_!': False,
 'x-sldB': False,
 '-n!pgDp=)}': False,
 "w9A!*m: ',": False,
 "'g|A1": False,
 "'p~$P`&f": False,
 'R-S4Zj7 UOofG_6': False,
 '7V"@h3Cx3o': False,
 '052iw4zZV\\k|a ]': False,
 '[i#B,O+$EN': False,
 '4NrCsvf2^}\\Q0': False,
 '4vQmvxsq77': True,
 '@g[H)(z7Dbs': False,
 '*fKUcHEHo': False,
 ':S5>!z': False,
 'TyNN 9/!b~-x?]': False,
 '&wu[[aIvu06zvB': False,
 'u2z8G *': False,
 '+tWE~<f/Ac': False,
 'W.w^, 1#4': False,
 '%|_mj,l-.Nv': False,
 '<}`+}': False,
 'qn~#xFujgB': False,
 'ja{eaX[f?': False,
 'UPgwyE!G> %[hJw': False,
 'G9)+Fg7l3%5@lv': False,
 ' c Ra;;HY2SrT': False,
 '1GjS>E^3GWS;S': False,
 '\\EUrir@2?~': False,
 ';(?(y^IOI;zZ8R': False,
 "a0&'V": False,
 '5Vtvpl.2<': False,
 'x9tECFb': True,
 '6FJIL{6\\<V+c': False,
 'No |{8': False,
 'Lxz4y=6%=UY': False,
 '1<xaU': False,
 '5st3DHk.d&': False,
 'mK2Y",h': False,
 '~_p6j&EUI-': False,
 '%=<J>u4:': False,
 'Th?tOY_)_=Lq': False,
 'G5{:sC': False,
 "X'XIa,Cp": False,
 '8|=|S!K-S|h%^': False,
 'H(8yoaud': False,
 '~f[Q-ER': False,
 ':w~7TY': False,
 'lI#b98sRr': False,
 '3]-"o. qvkR': False,
 '2s]%seW': False,
 'WBbQP;wtF/': False,
 'y_<}ST,MBO?': False,
 '0Bd<jiMS': False,
 '9Vn.3CeW4pt8': False,
 'b;fDIM': False,
 'O<,23qhS;Oh_p': False,
 'fmh`Y2': False,
 'e#6.+}=Y6': False,
 'e-[xgK%%7"x': False,
 '#VJNhv3:': False,
 '~eHHi': False,
 '&CsS]mT': False,
 '7ilOm': True,
 'jMA,k{O@B{cExw"': False,
 '&]9|U)': False,
 'I^Y*?N!PNE$4Vza': False,
 'v,~:&:?Z': False,
 'y4-?1Yo^D': False,
 'h, ]^3q.>iT': False,
 '+Ed{xf*': False,
 'n0WxFL^GHT6D\\yM': False,
 '>])Z.^L~': False,
 '&tqU!/o* b*EVL': False,
 'QIIsp#Nz=Z': False,
 'y)Z5HVtZ2': False,
 '-Tkz!>': False,
 'VPxxO1{BZc~DD!e': False,
 'p[0>\\jKo': False,
 '.my6xGq6T}{*$L': False,
 'Xe}&WP>i+x': False,
 'Y)mUn.-b*': False,
 '8?X|eu': False,
 '7q2zx,e@Le((|': False,
 ':dc"B.B9ggz_': False,
 '}emBOP!rF[" ': False,
 '1BL3yzH\\^?VR': False,
 '{Ks).e': False,
 '&Hqx)I]%c': False,
 'p$I$<o5md': False,
 '^CrN/|faTG<y': False,
 'G?Omk': False,
 " B.WSI':N\\9H7#": False,
 '6P>/fEeX.l,W': False,
 '%F0p]`a@_5:!p+g': False,
 '~F6 u% }ItUZPyf': False,
 'TgA{@ Ni\\n1Q': False,
 '%>bN}pWR4': False,
 'e(/hr}%j"?cO0': False,
 ':E3|OZ': False,
 'Bim 7aU': False,
 '5R#$SK`<d7d}': False,
 'Grzbz': True,
 '7M]V<3p': False,
 'Z}NIi,rRY)_2F2': False,
 '?a;[(yVau;': False,
 '/6_x=XHk!y{': False,
 '2E_oG': True,
 '>u,T ;w': False,
 '~=e lp6Ntg]': False,
 '~Ou9b";Ri1dIy': False,
 '"c 0; ZV\\5)': False,
 'dM3Ik6c(?1GY.': False,
 '{Y?[*9C': False,
 'iP)dTNh_LWZ)f$': False,
 'b+[B;k:<S8J': False,
 '3xea3;^/A(': False,
 'n6o}#rWXP': False,
 "-=&v6Yo_'gGFw": False,
 'W}WYp~cZ.Vc|}': False,
 'I{W_PLPr3Ryf$:': False,
 'A-\\VQ,jCyGKV9r': False,
 'cLjK51D#D': False,
 'f7*3F;Dh"g2': False,
 'Uu-PGr=GXs$%j !': False,
 'Q70K7': True,
 'q%`DJ,#2cC': False,
 'hZx g=v\\kZ|6P': False,
 '=&GK$*:AQ J_+A': False,
 '"+I]*hRw-+l@': False,
 '?q?FjW5Ytn': False,
 '6jV%fR+YHoV': False,
 "qRSy:#Hol=X'3h": False,
 "<tMKi7'yetPj9C": False,
 'pnO-R': False,
 '!V:6rb?9oj+': False,
 'Db,XRP&FF%1m': False,
 '5SAy^z': False,
 '*QMjW>|Z': False,
 "'BNZp$;p8": False,
 'uSG; +iNAgl1': False,
 '`; U{)]:Gr/': False,
 'hmA0fnlf<<V5g': False,
 "5'Dp8O*C|/\\4`?": False,
 'O3t |!9N`U`o': False,
 '#x^&ChAquNww8{;': False,
 'g~^b6/-j)NHR+': False,
 'Vv\\3JwXZ': False,
 '9cBdHd2hv`8': False,
 'oJ@EH7rCe/': False,
 '{LxGzy;L@-C': False,
 '#nePm@@]le?1nC(': False,
 '+<v5dxk+/w': False,
 ']1\\>-': False,
 '7o!9T/<Em$=M)': False,
 '.iWSZu0~`U': False,
 'g4U<z`,(\\ZW}o{': False,
 "HMa~z0'uCS'oAqI": False,
 'rs~(lHQ]7~': False,
 'q[*}X1\\+)': False,
 'nKugTp|mauN[W': False,
 "<{;_Q@]('!h?C61": False,
 'wgq%0': False,
 "j':JY": False,
 'V+`pbW': False,
 'h@^3.aXM?\\Hhu': False,
 '&us3S5b\\E+ZeT!:': False,
 '\\coh+=KcjTt#Q': False,
 '-\\E}m`a': False,
 'FWP[H?': False,
 'l!y+w}=it>XYm|': False,
 '|W)H@sWdVv}': False,
 's+m5i9tZ$EBqS': False,
 'U&"po9)tx>8|': False,
 'GiD]/c1p0y Yb': False,
 '.zj1y{6MG': False,
 '_EF.BGm]f9J#': False,
 'Nwa[HMO|H=C7': False,
 '%S:k#Th': False,
 '&[v1iw UL': False,
 "tDh)sp'~B": False,
 'zby9P9': True,
 'T8@&`Y*:RW': False,
 'p*7z#[v]W': False,
 'o&S>Jq]i!b28\\': False,
 't-MTf226{': False,
 '%bzEX': False,
 ',Maa\\UOX.3hc I': False,
 'L\\1e(%u': False,
 'HCB_DEls': True,
 'DHx/-+}G-,!': False,
 'kn>.lv RW{bCh{': False,
 'NCC{Q1 ` C': False,
 '}zOs ;c%4\\M+Q_H': False,
 'hM4z5WO': True,
 'HU14ud3': True,
 'G1|BH@yf<:X}s0J': False,
 '4~2|(|>6Mn&-': False,
 '.9@+0vZOc?{@Z5E': False,
 'B]<6--Aj': False,
 '?.kqzL': False,
 '@q?@(u84tn': False,
 'ZX"Nc>4yH{C@PS': False,
 'ldb%@': False,
 'IKC2vk(Pa(SDfY': False,
 '{u\\xgiyd).': False,
 '_a^"}A`': False,
 'YeE6Kmz2E9': True,
 '?IyVY9!vTWKd?jE': False,
 'qI;|%+&': False,
 'Ml22eJ/': False,
 '*s#,L': False,
 '14fY>': False,
 '`A3!0Gj`b=eo]Jv': False,
 'uno.S8B_3i': False,
 'rK|OIXP~ ?/0': False,
 '\\zp6ap': False,
 'GMg0-WQG?.': False,
 'y{)%$gx754kc"Kk': False,
 '\\vULa0*j': False,
 's\\2s#}oC$Zzg)e': False,
 'JD+rZ5[9cx.5r f': False,
 '?(mC*g7TLFZD': False,
 "gd/e%*':7": False,
 '" P%<e<(Z]': False,
 'AFrkp': True,
 'Y|H?Fs': False,
 'im6u_': True,
 'KP.8ZFhiDT': False,
 ')X8zde}m%': False,
 'mIy.^': False,
 'Ca#iXqQ;syHFs)u': False,
 '\'!@i&X"nxKo': False,
 ')C!fQa^|%$P4!': False,
 'neVQM:eii+BBhM.': False,
 'r59A,2D7[': False,
 '`2A#fp1+uBIj~@6': False,
 '_f#ehq{4yrFM': False,
 "U5$;E'~FO=t|@": False,
 'U6FxTI]eJM2.': False,
 'M`fg^&': False,
 '+Fs,>+3 xZL$Brm': False,
 'kp;}gs^%C&0y': False,
 'X58#V_P6': False,
 'b]e(,cTk[/iO': False,
 'YQu)b:-': False,
 '?)o1QzqDBU^gFR': False,
 'Tucf6}': False,
 'Ha4)^&': False,
 'V|}sc|1': False,
 '<_nlH^"^&,Ao"/': False,
 'L6FV@sT': False,
 ")1y4'%J": False,
 '&z/Gk<Jg_?VB\\': False,
 'iG\\):R47bo': False,
 'wL^]m': False,
 '8JYU6J-;X`g.E': False,
 'IEX xs~@c^he': False,
 "@1f:rj:?RB'Q": False,
 't)[,P"u': False,
 '|GjmETs0': False,
 '{_&G5j\\': False,
 'U&_tXkm8Rin': False,
 '+OF\'ig-}"K0V49l': False,}

FITNESS_PARAMS = {'test_cases' : TEST_CASES}

GENES = ''.join([chr(x) for x in range(32,126)])

def FITNESS(string, test_cases):
    iters = len(test_cases)
    
    score = 0
    try:
        for key, value in test_cases.items():
            score += int(bool(re.match(string, key)) == value)
    except:
        return -1
    return score / iters